#!/usr/bin/env python

# Copyright 2015 The Baker Street Authors. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from roy import build, deps
from pkg_common import Common
import _metadata

class Sherlock(Common):

    def __init__(self):
        self.name = "datawire-sherlock"
        self.version = _metadata.__version__
        self.build_deps = []
        self.deps = [deps.datawire, deps.haproxy, deps.policycoreutils]
        self.arch = "all"
        self.conf = ["/etc/datawire/sherlock.conf"]
        self.iteration = 1
        self.postinstall = """
/usr/sbin/setsebool -P haproxy_connect_any on || true
/usr/bin/chcon --type haproxy_var_run_t /opt/datawire/run || true
"""

    def build(self, distro):
        result = self.install_prep()
        result += """
cp _metadata.py /work/install/opt/datawire/lib
"""
        result += self.install_script("sherlock")
        result += self.install_config(self.name, distro.image)
        return result

build(Sherlock())
