#!/usr/bin/env python

# Copyright 2015 The Baker Street Authors. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Watson

- Periodically GET a URL
- Tether to the directory if GET was successful
"""

import urllib2
import logging
import re
from argparse import ArgumentParser

from proton.reactor import Reactor

from datawire import Configuration, Tether

from _metadata import __version__

logging.basicConfig(datefmt="%Y-%m-%d %H:%M:%S",
                    format="%(asctime)s watson %(name)s %(levelname)s %(message)s")
log = logging.getLogger()


class LivenessByHTTPGet(object):

    def __init__(self, url):
        self.url = url
        self.okay = set([200])

    def __call__(self):
        try:
            res = urllib2.urlopen(self.url)
            if res.getcode() in self.okay:
                return True
        except urllib2.URLError:
            pass
        return False


class Watson(object):

    def __init__(self, args, testLiveness):
        self.tetherArgs = args.directory, args.address, args.service_url
        self.tether = None
        self.testingPeriod = args.period
        self.testLiveness = testLiveness
        self.justStarted = True
        self.url = args.service_url

    def on_reactor_init(self, event):
        event.reactor.schedule(0, self)

    def on_timer_task(self, event):
        if self.testLiveness():
            # Alive
            if self.tether is None:
                # Just came to life
                log.info("DEAD -> LIVE (%s)", self.url)
                self.tether = Tether(*self.tetherArgs)
                self.tether.start(event.reactor)
        else:
            # Dead
            if self.tether is not None:
                # Just died
                log.info("LIVE -> DEAD (%s)", self.url)
                self.tether.stop(event.reactor)
                self.tether = None
                log.debug(" liveness check at %s for service %s", self.testLiveness.url, self.url)
            elif self.justStarted:
                log.info("START -> DEAD (%s)", self.url)
                self.justStarted = False
                log.debug("liveness check at %s for service %s", self.testLiveness.url, self.url)
        event.reactor.schedule(self.testingPeriod, self)

default_config = """
[DEFAULT]
logging: WARNING

[Datawire]
directory_host:

[Watson]
period: 3
"""

def create_config_fail_message(reason=None):
    return "Failed to load configuration%s" % (": %s." % reason if reason else ".")


def validate_service_name(config_loader, service_name):

    """
    Checks that a service name is not empty or all whitespace as well as whether the service name fits certain
    requirements such as beginning with a a letter or underscore and that the overall service name is no longer than
    one hundred characters.

    :param config_loader: the configuration loader
    :param service_name: the name of the service to validate
    :return: None
    """

    pattern = re.compile("^([a-z_])([a-z0-9_-]*)$")
    if not service_name or service_name.isspace() or not pattern.match(service_name) or len(service_name) > 100:
        log.exception(create_config_fail_message("invalid service name"))
        config_loader.exit_with_config_error("Configuration error: invalid service name; not defined or did not match "
                                             "pattern (pattern: %s)" % pattern.pattern)


def main():
    parser = ArgumentParser()
    parser.add_argument("-c", "--config", help="read from additional config file", metavar="FILE")
    parser.add_argument("-V", "--version", action="version", version="%(prog)s " + __version__)
    args = parser.parse_args()

    loader = Configuration(default_config)
    loader.add_file_relative("watson.conf")
    if args.config:
        loader.add_file_absolute(args.config)

    config = loader.parse()
    if not loader.parsed_filenames:
        loader.exit_with_config_error(create_config_fail_message("configuration not found"))

    try:
        args.directory_host = config.get("Datawire", "directory_host")
        args.period = config.getint("Watson", "period")
        args.logging = config.get("Watson", "logging")
    except Exception:
        log.exception("Failed to load configuration")
        loader.exit_with_config_error(create_config_fail_message())

    if args.period < 1:
        args.period = 1
        log.warning("Setting service check period to minimum value of one second.")

    try:
        args.service_url = config.get("Watson", "service_url")
        args.service_name = config.get("Watson", "service_name")
        args.liveness_url = config.get("Watson", "liveness_url")
    except Exception:
        loader.exit_with_config_error("Configuration error: Ensure service_url, service_name, and liveness_url "
                                      "are configured.")

    validate_service_name(loader, args.service_name)

    log.setLevel(getattr(logging, args.logging.upper()))
    if not args.directory_host:
        log.warning("No directory_host configured. Falling back to localhost.")
        args.directory_host = "localhost"

    args.directory = "//%s/directory" % args.directory_host
    args.address = "//%s/%s" % (args.directory_host, args.service_name)

    checker = LivenessByHTTPGet(args.liveness_url)

    log.info("Starting Watson... (directory: %s, service_name: %s, service_url: %s, health: %s)" % (args.directory,
                                                                                                    args.service_name,
                                                                                                    args.service_url,
                                                                                                    args.liveness_url))

    Reactor(Watson(args, checker)).run()

if __name__ == "__main__":
    main()
